// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnM1LQllha4KE5623aNWPgZ-VWUVlzSRo',
    appId: '1:566683942428:android:d0747f5a8624423515a9d9',
    messagingSenderId: '566683942428',
    projectId: 'movieflutter-dc2bd',
    storageBucket: 'movieflutter-dc2bd.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8AgNpPU70kJTUf_ZWi1dby53E5DlENXM',
    appId: '1:566683942428:web:18e18f21d1868a5e15a9d9',
    messagingSenderId: '566683942428',
    projectId: 'movieflutter-dc2bd',
    authDomain: 'movieflutter-dc2bd.firebaseapp.com',
    storageBucket: 'movieflutter-dc2bd.firebasestorage.app',
    measurementId: 'G-3T23NX4KDX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPcO___VJSwz6XmnKEU0ltqd25IjVhoTo',
    appId: '1:566683942428:ios:c12613d56bf707ca15a9d9',
    messagingSenderId: '566683942428',
    projectId: 'movieflutter-dc2bd',
    storageBucket: 'movieflutter-dc2bd.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8AgNpPU70kJTUf_ZWi1dby53E5DlENXM',
    appId: '1:566683942428:web:4ad3a66a1b68d33f15a9d9',
    messagingSenderId: '566683942428',
    projectId: 'movieflutter-dc2bd',
    authDomain: 'movieflutter-dc2bd.firebaseapp.com',
    storageBucket: 'movieflutter-dc2bd.firebasestorage.app',
    measurementId: 'G-XS77PJX5KX',
  );
}
